version: '3'

networks:
  strapi:

services:
  # Development service
  # Comment/remove development service block when deploying to production
  development:
    image: node:latest
    container_name: development
    volumes:
      - ./:/var/www/strapi
    working_dir: /var/www/strapi
    command: >
      bash -c "node -v
      && yarn -v
      && yarn install
      && yarn develop"
    ports:
      - "8001:8000"
    expose: 
      - "8001"
    networks:
      - strapi

  #MYSQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: on-failure
    tty: true
    ports:
      - "3366:3306"
    expose:
      - "3366"
    environment:
      MYSQL_DATABASE: db_strapi
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: nq2w6qMnYzGM7,b1*G>0
      MYSQL_PASSWORD: nq2w6qMnYzGM7,b1*G>0
    networks:
      - strapi
  
  # Production service
  # Comment production service block during developing your app in local
  # Remove depends_on in production
  production:
    image: node:latest
    container_name: production
    volumes:
      - ./:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    command: >
      bash -c "node -v
      && yarn -v
      && yarn install
      && yarn build"
    networks:
      - strapi

  # NGINX service
  # Comment NGINX service block when developing your app in local
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "8002:80"
    expose:
      - "8002"
    volumes:
      - ./:/usr/share/nginx/html
      - ./docker_services_config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker_services_config/nginx/logs/access.log:/var/log/nginx/access.log
      - ./docker_services_config/nginx/logs/error.log:/var/log/nginx/error.log
    links:
      - production
    depends_on: 
      - production
    networks:
      - strapi

 
